spring:
  datasource:
    url: jdbc:h2:mem:gogodb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    database-platform: org.hibernate.dialect.H2Dialect


  jwt:
    secretKey: ${SECRET_KEY}
    refreshKey: ${REFRESH_KEY}
    accessExp: ${ACCESS_EXP}
    refreshExp: ${REFRESH_EXP}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

gauth:
  clientId: ${CLIENT_ID}
  clientSecret: ${CLIENT_SECRET}
  redirectUrl: ${REDIRECT_URL}
  authUrl: ${AUTH_URL}
  userApiUrl: ${USER_API_URL}

cookie-domain: localhost

message:
  apiKey: ${API_KEY}
  apiSecretKey: ${API_SECRET_KEY}
  send: ${SEND_NUMBER}

server:
  port: 8090