spring:
  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        show_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  jwt:
    secretKey: ${SECRET_KEY}
    refreshKey: ${REFRESH_KEY}
    accessExp: ${ACCESS_EXP}
    refreshExp: ${REFRESH_EXP}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

gauth:
  clientId: ${CLIENT_ID}
  clientSecret: ${CLIENT_SECRET}
  redirectUrl: ${REDIRECT_URL}
  authUrl: ${AUTH_URL}
  userApiUrl: ${USER_API_URL}

cookie-domain: localhost

message:
  apiKey: ${API_KEY}
  apiSecretKey: ${API_SECRET_KEY}
  send: ${SEND_NUMBER}
server:
  port: 5173
