name: CD
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and deploy gsmgogo-api module
        run: |
          cd GSM-GOGO-Server/gsmgogo-api
          ./gradlew clean build
          docker build -t gsmgogo/gsmgogo-api . -f Api.dockerfile
          docker stop gogo-api || true
          docker rm gogo-api || true
          docker run -d -it --env-file ./.env -p 10001:8080 --name gogo-api gsmgogo/gsmgogo-api

      - name: Build and deploy gsmgogo-batch module
        run: |
          cd GSM-GOGO-Server/gsmgogo-batch
          ./gradlew clean build
          docker build -t gsmgogo/gsmgogo-batch . -f Batch.dockerfile
          docker stop gogo-batch || true
          docker rm gogo-batch || true
          docker run -d -it --env-file ./.env -p 10002:8081  --name gogo-batch gsmgogo/gsmgogo-batch