name: CD
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: excuting remote ssh commands
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            cd /home/ubuntu/GSM-GOGO-Server
            git pull origin main
            docker stop gogo-server
            docker build -t gsmgogo/gsmgogo-server .
            docker run -d -it --env-file ./.env -p 8080:8080 --name gogo-server gsmgogo/gsmgogo-server