name: CD
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: excuting remote ssh commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_IP }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          username: ${{ secrets.REMOTE_USERNAME }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          script: |
            cd /home/ubuntu/GSM-GOGO-Server
            git pull origin main
            ./gradlew clean
            ./gradlew build
            docker stop gogo-api || true
            docker rm gogo-api || true
            docker stop gogo-batch || true
            docker rm gogo-batch || true
            docker build -t gsmgogo/gsmgogo-api . -f Api.dockerfile
            docker build -t gsmgogo/gsmgogo-batch . -f Batch.dockerfile
            docker run -d -it --env-file ./.env -p 10001:8080 --name gogo-api gsmgogo/gsmgogo-api
            docker run -d -it --env-file ./.env --name gogo-batch gsmgogo/gsmgogo-batch